[package]
name = "ti-sbl"
version = "0.1.0"
authors = ["Locha Mesh Developers <contact@locha.io>"]
edition = "2018"

[workspace]
members = ["prog-cli"]

[dependencies]
serial = "0.4"
log = "0.4"

[target.'cfg(target_os = "linux")'.dependencies]
glob = "0.3"
